### ISSUE TITLE
Launching Docker-based development environment locally fails with an error

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/bibxml-service#311]
### Describe the issue

The error makes all development problematic due to inability to launch the service locally.

The error happens when container `celery` is started:

```
Error response from daemon: failed to initialize logging driver: Unix syslog delivery error
```

I suspect it may have to do with this part of the Compose file:

```
    logging:
      driver: "syslog"
      options:
        syslog-address: "${SYSLOG}"
```

Is there a new dependency that I missed that is required for this to work?

cc @kesara 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
