### ISSUE TITLE
Update to relaton v1.19.*

### ISSUE THREAD

**Issue by kesara** [ietf-tools/bibxml-service#467]
### Description

Changing to relaton `v1.19.2` seem to have the following updates:

### `doctype`
Previous:
```
doctype: <string>
```
New:
```
doctype:
  type: <string>
```

Previous:
```
place:
- <string>
```

### `place`
New:
```
place:
- city: <string>
  region:
  - name: <string>
    iso: <string>
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
